package enumify

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"go/types"
	"path/filepath"
	"strings"

	g "github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

type Enum interface {
	fmt.Stringer
	json.Marshaler
	json.Unmarshaler
	sql.Scanner
	driver.Valuer
}

// Options defines how the code generation should be performed. These values are set by
// the CLI flags passed via the go generate directive.
type Options struct {
	File       string // The file that kicked off the generation (from $GOFILE)
	Pkg        string // The package that the enum is in (from $GOPACKAGE)
	NameVar    string // The variable name that contains the names of the enum values
	NoTests    bool   // Whether to skip the testing code generation (defaults to false)
	NoParser   bool   // Whether to skip the parser code generation (defaults to false)
	NoStringer bool   // Whether to skip the Stringer interface code generation (defaults to false)
	NoText     bool   // Whether to skip the text interfaces code generation (defaults to false)
	NoBinary   bool   // Whether to skip the binary interfaces code generation (defaults to false)
	NoJSON     bool   // Whether to skip the JSON interfaces code generation (defaults to false)
	NoYAML     bool   // Whether to skip the YAML interfaces code generation (defaults to false)
	NoSQL      bool   // Whether to skip the SQL interfaces code generation (defaults to false)
}

func GenerateComment() string {
	return fmt.Sprintf("Code generated by enumify v%s. DO NOT EDIT.", Version())
}

func Generate(opts Options) (err error) {
	f := g.NewFile(opts.Pkg)
	f.PackageComment(GenerateComment())

	if _, err = opts.discover(); err != nil {
		return err
	}

	if err = f.Save(opts.fileName()); err != nil {
		return err
	}
	return nil
}

func GenerateTests(opts Options) (err error) {
	f := g.NewFile(opts.Pkg + "_test")
	f.PackageComment(GenerateComment())

	if err = f.Save(opts.testFileName()); err != nil {
		return err
	}
	return nil
}

func (o Options) fileName() string {
	ext := filepath.Ext(o.File)
	return strings.TrimSuffix(filepath.Base(o.File), ext) + "_gen" + ext
}

func (o Options) testFileName() string {
	ext := filepath.Ext(o.File)
	return strings.TrimSuffix(filepath.Base(o.File), ext) + "_gen_test" + ext
}

func (o *Options) discover() (etypes EnumTypes, err error) {
	// Build tool package discovery configuration.
	cfg := &packages.Config{
		Mode: packages.NeedTypes | packages.NeedTypesInfo,
	}

	// NOTE: do not use the driver query file={os.File} here because it will load the
	// entire package instead of just the contents of the file. As a result, the
	// types discovered by packages.Load will have the package "command-line-arguments"
	// scope rather than the scope of the package being inspected.
	//
	// We prefer this so we can isolate the specific files that have a go generate
	// directive and ignore the other files including other files that may also have
	// go generate directives.
	//
	// TODO: what if multiple enums are defined in the same file?
	var pkgs []*packages.Package
	if pkgs, err = packages.Load(cfg, o.File); err != nil {
		return nil, fmt.Errorf("failed to load package %q for inspection: %w", o.File, err)
	}

	if len(pkgs) == 0 {
		return nil, fmt.Errorf("no packages found for inspection")
	}

	if len(pkgs) > 1 {
		return nil, fmt.Errorf("multiple packages found for inspection: %v", pkgs)
	}

	gopkg := pkgs[0]
	if len(gopkg.Errors) > 0 {
		return nil, fmt.Errorf("package errors: %v", pkgs[0].Errors)
	}

	// Get the predeclared uint8 type for comparison
	uint8Type := types.Typ[types.Uint8]

	// First pass: discover all the enum types in the package.
	// An enum type is a type whose underlying type is uint8.
	etypes = make(EnumTypes, 0, 1)
	scope := gopkg.Types.Scope()
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		if typ, ok := obj.(*types.TypeName); ok {
			if types.Identical(typ.Type().Underlying(), uint8Type) {
				etypes = append(etypes, &EnumType{
					Name:  name,
					Type:  obj.Type(),
					gopkg: gopkg,
					scope: scope,
				})
			}
		}
	}

	// Second pass: populate the enum types with consts and the name variable.
	for _, etype := range etypes {
		// Discover the consts and names variable for the enum type.
		etype.discover()

		// If the names variable is not set, but one was passed in from the command
		// line, then attempt to set it on the enum type.
		if etype.NamesVar == nil && o.NameVar != "" {
			if err = etype.setNamesVar(o.NameVar); err != nil {
				return nil, fmt.Errorf("failed to set names variable for enum type %q: %w", etype.Name, err)
			}
		}

		// The enum type must be valid before we can generate code for it.
		if err = etype.validate(); err != nil {
			return nil, err
		}
	}
	return etypes, nil
}
