package enumify

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type Enum interface {
	fmt.Stringer
	json.Marshaler
	json.Unmarshaler
	sql.Scanner
	driver.Valuer
}

// Options defines how the code generation should be performed. These values are set by
// the CLI flags passed via the go generate directive.
type Options struct {
	File       string // The file that kicked off the generation (from $GOFILE)
	Pkg        string // The package that the enum is in (from $GOPACKAGE)
	NameVar    string // The variable name that contains the names of the enum values
	NoTests    bool   // Whether to skip the testing code generation (defaults to false)
	NoParser   bool   // Whether to skip the parser code generation (defaults to false)
	NoStringer bool   // Whether to skip the Stringer interface code generation (defaults to false)
	NoText     bool   // Whether to skip the text interfaces code generation (defaults to false)
	NoBinary   bool   // Whether to skip the binary interfaces code generation (defaults to false)
	NoJSON     bool   // Whether to skip the JSON interfaces code generation (defaults to false)
	NoYAML     bool   // Whether to skip the YAML interfaces code generation (defaults to false)
	NoSQL      bool   // Whether to skip the SQL interfaces code generation (defaults to false)
}

func GenerateComment() string {
	return fmt.Sprintf("Code generated by enumify v%s. DO NOT EDIT.", Version())
}

func Generate(opts Options) error {
	fmt.Printf("%+v\n", opts)
	return nil
}

func GenerateTests(opts Options) error {
	return nil
}
